# Generated by Django 2.1.4 on 2019-01-04 09:57

from django.db import migrations, models
import django.db.models.deletion
import serviceapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadId', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(blank=True, max_length=30)),
                ('emailId', models.CharField(blank=True, max_length=12)),
                ('contactNumber', models.CharField(max_length=12)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('remarks', models.CharField(max_length=500)),
                ('callStatus', models.CharField(choices=[(serviceapp.models.CallStatus('Non Qualified'), 'Non Qualified'), (serviceapp.models.CallStatus('Cold Call'), 'Cold Call'), (serviceapp.models.CallStatus('Qualified Call'), 'Qualified Call'), (serviceapp.models.CallStatus('Warm Call'), 'Warm Call'), (serviceapp.models.CallStatus('Hot Call'), 'Hot Call'), (serviceapp.models.CallStatus('Converted'), 'Converted')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roleId', models.IntegerField()),
                ('roleName', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(blank=True, max_length=30)),
                ('emailId', models.CharField(blank=True, max_length=12)),
                ('contactNumber', models.CharField(blank=True, max_length=12)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('userId', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.Roles')),
            ],
        ),
        migrations.AddField(
            model_name='leads',
            name='assignedTo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceapp.Users'),
        ),
    ]
