# Generated by Django 2.1.4 on 2019-01-04 11:02

from django.db import migrations, models
import serviceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='callStatus',
            field=models.CharField(choices=[(serviceapp.models.CallStatus('Non Qualified'), 'Non Qualified'), (serviceapp.models.CallStatus('Cold Call'), 'Cold Call'), (serviceapp.models.CallStatus('Qualified Call'), 'Qualified Call'), (serviceapp.models.CallStatus('Warm Call'), 'Warm Call'), (serviceapp.models.CallStatus('Hot Call'), 'Hot Call'), (serviceapp.models.CallStatus('Converted'), 'Converted')], default=serviceapp.models.CallStatus('Qualified Call'), max_length=25),
        ),
    ]
