# Generated by Django 2.1.4 on 2019-01-04 11:04

from django.db import migrations, models
import serviceapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('serviceapp', '0002_auto_20190104_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leads',
            name='callStatus',
            field=models.CharField(choices=[('NON_QUALIFIED', 'Non Qualified'), ('COLD_CALL', 'Cold Call'), ('QUALIFIED_CALL', 'Qualified Call'), ('WARM_CALL', 'Warm Call'), ('HOT_CALL', 'Hot Call'), ('CONVERTED', 'Converted')], default=serviceapp.models.CallStatus('Qualified Call'), max_length=25),
        ),
    ]
